version: "3"
services:
    mongo:
        image: mongo:latest
        ports: ["27017:27017"]
    redis:
        image: redis:latest
        ports: ["6379:6379"]
    web:
        build:
            dockerfile: docker/dev.docker
            context: ..
        depends_on: [mongo, redis]
        ports: ["80:80"]
        volumes: ["..:/app"]
