version: "3"
services:
    mongo:
        image: mongo:latest
    redis:
        image: redis:latest
    web:
        build:
            dockerfile: docker/dev.docker
            context: ..
        depends_on:
            - mongo
            - redis
        ports:
            - "80:80"
        volumes:
            - "..:/app"
