version: "3"
services:
    mongo:
        image: mongo:latest
    redis:
        image: redis:latest
    web:
        build:
            dockerfile: docker/pro.docker
            context: ..
        ports:
            - "80:80"
